// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxwcqocxqmajxpkmycox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4d2Nxb2N4cW1hanhwa215Y294Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MjEyODQsImV4cCI6MjA2MDQ5NzI4NH0.ZGspuBFBFztjiF7Vf27vmAm1OfrrHqo6EEduDdxI_yo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);